In [2]:
!pip install numpy

### Load in NumPy (remember to pip install numpy first)

In [107]:
import numpy as np

### The Basics

In [201]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [192]:
b = np.array([[9.0,8.0,7.0],
              [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [194]:
b[1, 1:]

array([5., 4.])

In [195]:
# Get Dimension
a.ndim

1

In [197]:
a.shape

(3,)

In [196]:
# Get Shape
b.shape

(2, 3)

In [198]:
# Get Type
a.dtype

dtype('int32')

In [199]:
# Get Size
a.itemsize

4

In [202]:
# Get total size
a.nbytes

6

In [203]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [204]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [205]:
# Get a specific element [r, c]
a[1, :2]

array([8, 9])

In [206]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [207]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1: 2]

array([2, 4, 6])

In [208]:
a[1, 5] = 20

a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [209]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [210]:
# Get specific element (work outside in)
b[0,1,1]

4

In [211]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [212]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [213]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [214]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [215]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [216]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [217]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [218]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.06124067, 0.124293  ],
       [0.22188307, 0.99716113],
       [0.1184472 , 0.14366346],
       [0.93511225, 0.53575268]])

In [143]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1, -3,  3],
       [-4,  1,  2],
       [-4, -3,  3]])

In [145]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [219]:
# Repeat an array
arr = np.array([[1,2,3]])

r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [148]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [223]:
a = np.array([1,2,3])
b = a.copy()

b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [225]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [226]:
a + 2

array([3, 4, 5, 6])

In [158]:
a

array([3, 4, 5, 6])

In [159]:
a - 2

array([1, 2, 3, 4])

In [160]:
a * 2

array([ 6,  8, 10, 12])

In [227]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [230]:
a ^ 2 

array([3, 0, 1, 6])

In [233]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [234]:
a ** 2

array([ 1,  4,  9, 16])

In [235]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [58]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [236]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [238]:
# Find the determinant
c = np.identity(3)

np.linalg.det(c)

1.0

In [61]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [169]:
stats = np.array([[1,2,3],
                  [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
np.min(stats)

1

In [239]:
np.max(stats, axis=1)

array([3, 6])

In [242]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing Arrays

In [177]:
before = np.array([[1,2,3,4],
                   [5,6,7,8]])
print(before)

after = before.reshape((2, 1, 4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3 4]]

 [[5 6 7 8]]]


In [97]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [178]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [179]:
# Load the CSV file

filedata = np.genfromtxt('data.csv', delimiter=',')

filedata = filedata.astype('int32')

print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [106]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [184]:
filedata[~((filedata > 50) & (filedata < 100))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int32)